### ISSUE TITLE
Submit to npm

### ISSUE THREAD

**Issue by neverfox** [ianstormtaylor/bump#4]
Is it possible to submit this to npm? I know there is already a bump out there and that would require a different package name, but npm doesn't appear to know, once it's installed, that it came from github. When checking for updates, it reverts to installing the package named `bump` from npm. I can update it with the namespace manually, but if I ever need to do a general `npm -g update`, it gets overwritten.

**Comment by dominicbarnes** [comment]
+1 to grabbing the name `semver-bump` or `bump-semver`.

**Comment by ianstormtaylor** [comment]
just asked the owner of the current `bump` name if he'd be down to switch it for this one. let's see what he says first and then we can decide! would love to get the simple/cleanest name if possible

**Comment by dominicbarnes** [comment]
Definitely! Let me know what he says :)

**Comment by ianstormtaylor** [comment]
Kk @dominicbarnes he wasn't interested in swapping. Let's go with `bump-version` as the name?

**Comment by neverfox** [comment]
I love it. That's actually the commit message I write every time I use this.

On July 23, 2015 7:09:14 PM EDT, "Ian Storm Taylor - notifications@github.com" <github.soma.3d1062736b.notifications#github.com@ob.0sg.net> wrote:
>Kk @dominicbarnes he wasn't interested in swapping. Let's go with
>`bump-version` as the name?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ianstormtaylor/bump/issues/4#issuecomment-124262652

-- 
Sent from my Android device. Please excuse my brevity.

**Comment by dominicbarnes** [comment]
All right! I've renamed the package to `bump-version` and published `0.4.2` to npm! (see a3fee2ac768e0af612b2cff334a8d024c1c28323)

(you can find it on npm [here](https://www.npmjs.com/package/bump-version))
