### ISSUE TITLE
Add machine-friendly mode to CLI

### ISSUE THREAD

**Issue by dominicbarnes** [ianstormtaylor/bump#7]
When scripting releases, it becomes a pain to use `bump` because it outputs human-friendly text all the time. It would be nice if there was a machine-friendly way to use it:

```sh
$ bump minor --print-version
1.2.0

$ bump patch --print-manifests
package.json
component.json
```

I'm not sure what the best API would be for this, but currently needing to use egrep to extract the new version number is awkward.

**Comment by ianstormtaylor** [comment]
Ah that's a cool idea! Happy to give you commit access if you wanna figure out the best solution and implement!

**Comment by dominicbarnes** [comment]
I'd love commit access! We can get this published to npm and get this feature in there :)

**Comment by ianstormtaylor** [comment]
just added you! 

let's wait on the naming, in case we can secure `bump`, but then if not we'll find a fallback

**Comment by dominicbarnes** [comment]
Added `--print-version` as part of `0.5.0` :)
